CREATE OR REPLACE DATABASE RETAIL_INTELLIGENCE_DB;

CREATE OR REPLACE SCHEMA RETAIL_INTELLIGENCE_DB.RAW;
CREATE OR REPLACE SCHEMA RETAIL_INTELLIGENCE_DB.STAGING;
CREATE OR REPLACE SCHEMA RETAIL_INTELLIGENCE_DB.MART;

-- FILE FORMAT

Use schema raw;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = JSON;

-- =====================================================
-- 5. STAGING TABLES
-- =====================================================

CREATE OR REPLACE TABLE STAGING.STG_PRODUCTS (
    PRODUCT_ID      STRING,
    PRODUCT_NAME    STRING,
    CATEGORY        STRING,
    SUBCATEGORY     STRING,
    BRAND           STRING,
    UNIT_COST       NUMBER(10,2),
    UNIT_PRICE      NUMBER(10,2),
    SIZE            STRING,
    COLOR           STRING
);

CREATE OR REPLACE TABLE STAGING.STG_STORES (
    STORE_ID        STRING,
    STORE_NAME      STRING,
    CITY            STRING,
    STATE           STRING,
    REGION          STRING,
    STORE_TYPE      STRING,
    OPENED_YEAR     NUMBER(4,0)
);

CREATE OR REPLACE TABLE STAGING.STG_SALES (
    TRANSACTION_ID       STRING,
    TRANSACTION_DATE     DATE,
    STORE_ID             STRING,
    PRODUCT_ID           STRING,
    UNITS_SOLD           NUMBER(10,0),
    GROSS_SALES_AMOUNT   NUMBER(12,2),
    DISCOUNT_AMOUNT      NUMBER(12,2),
    SALES_AMOUNT         NUMBER(12,2),
    SALES_CHANNEL        STRING
);

CREATE OR REPLACE TABLE STAGING.STG_INVENTORY (
    SNAPSHOT_DATE        DATE,
    STORE_ID             STRING,
    PRODUCT_ID           STRING,
    AVAILABLE_STOCK      NUMBER(10,0),
    ON_HAND_STOCK        NUMBER(10,0),
    RESERVED_STOCK       NUMBER(10,0),
    COMMITTED_STOCK      NUMBER(10,0),
    INVENTORY_ON_ORDER   NUMBER(10,0),
    SAFETY_STOCK         NUMBER(10,0)
);

CREATE OR REPLACE TABLE STAGING.STG_SUPPLIER_LEAD_TIMES (
    PRODUCT_ID           STRING,
    SUPPLIER_NAME        STRING,
    LEAD_TIME_DAYS       NUMBER(10,0),
    REORDER_THRESHOLD    NUMBER(10,0),
    PREFERRED_SUPPLIER   BOOLEAN,
    MINIMUM_ORDER_QTY    NUMBER(10,0)
);

-- =====================================================
-- 6. MART TABLES
-- =====================================================

CREATE OR REPLACE TABLE MART.DIM_PRODUCT (
    PRODUCT_ID      STRING,
    PRODUCT_NAME    STRING,
    CATEGORY        STRING,
    SUBCATEGORY     STRING,
    BRAND           STRING,
    SIZE            STRING,
    COLOR           STRING,
    UNIT_COST       NUMBER(10,2),
    UNIT_PRICE      NUMBER(10,2)
);

CREATE OR REPLACE TABLE MART.DIM_STORE (
    STORE_ID        STRING,
    STORE_NAME      STRING,
    CITY            STRING,
    STATE           STRING,
    REGION          STRING,
    STORE_TYPE      STRING,
    OPENED_YEAR     NUMBER(4,0)
);

CREATE OR REPLACE TABLE MART.FACT_SALES (
    TRANSACTION_ID       STRING,
    TRANSACTION_DATE     DATE,
    STORE_ID             STRING,
    PRODUCT_ID           STRING,
    UNITS_SOLD           NUMBER(10,0),
    GROSS_SALES_AMOUNT   NUMBER(12,2),
    DISCOUNT_AMOUNT      NUMBER(12,2),
    SALES_AMOUNT         NUMBER(12,2),
    SALES_CHANNEL        STRING
);

CREATE OR REPLACE TABLE MART.FACT_INVENTORY_DAILY (
    SNAPSHOT_DATE        DATE,
    STORE_ID             STRING,
    PRODUCT_ID           STRING,
    AVAILABLE_STOCK      NUMBER(10,0),
    ON_HAND_STOCK        NUMBER(10,0),
    RESERVED_STOCK       NUMBER(10,0),
    COMMITTED_STOCK      NUMBER(10,0),
    INVENTORY_ON_ORDER   NUMBER(10,0),
    SAFETY_STOCK         NUMBER(10,0)
);

-- =====================================================
-- 7. OPTIONAL: DATE DIMENSION TABLE
-- =====================================================

CREATE OR REPLACE TABLE MART.DIM_DATE (
    DATE_DAY         DATE,
    YEAR_NUM         NUMBER(4,0),
    QUARTER_NUM      NUMBER(1,0),
    MONTH_NUM        NUMBER(2,0),
    MONTH_NAME       STRING,
    WEEK_NUM         NUMBER(2,0),
    DAY_OF_MONTH     NUMBER(2,0),
    DAY_OF_WEEK      NUMBER(1,0),
    DAY_NAME         STRING
);