USE WAREHOUSE RETAIL_PROJECT;
USE DATABASE RETAIL_INTELLIGENCE_DB;

CREATE OR REPLACE TABLE MART.DIM_PRODUCT (
    PRODUCT_ID      STRING,
    PRODUCT_NAME    STRING,
    CATEGORY        STRING,
    SUBCATEGORY     STRING,
    BRAND           STRING,
    SIZE            STRING,
    COLOR           STRING,
    UNIT_COST       NUMBER(10,2),
    UNIT_PRICE      NUMBER(10,2)
);

CREATE OR REPLACE TABLE MART.DIM_STORE (
    STORE_ID        STRING,
    STORE_NAME      STRING,
    CITY            STRING,
    STATE           STRING,
    REGION          STRING,
    STORE_TYPE      STRING,
    OPENED_YEAR     NUMBER(4,0)
);

CREATE OR REPLACE TABLE MART.FACT_SALES (
    TRANSACTION_ID       STRING,
    TRANSACTION_DATE     DATE,
    STORE_ID             STRING,
    PRODUCT_ID           STRING,
    UNITS_SOLD           NUMBER(10,0),
    GROSS_SALES_AMOUNT   NUMBER(12,2),
    DISCOUNT_AMOUNT      NUMBER(12,2),
    SALES_AMOUNT         NUMBER(12,2),
    SALES_CHANNEL        STRING
);

CREATE OR REPLACE TABLE MART.FACT_INVENTORY_DAILY (
    SNAPSHOT_DATE        DATE,
    STORE_ID             STRING,
    PRODUCT_ID           STRING,
    AVAILABLE_STOCK      NUMBER(10,0),
    ON_HAND_STOCK        NUMBER(10,0),
    RESERVED_STOCK       NUMBER(10,0),
    COMMITTED_STOCK      NUMBER(10,0),
    INVENTORY_ON_ORDER   NUMBER(10,0),
    SAFETY_STOCK         NUMBER(10,0)
);

CREATE OR REPLACE TABLE MART.DIM_DATE (
    DATE_DAY         DATE,
    YEAR_NUM         NUMBER(4,0),
    QUARTER_NUM      NUMBER(1,0),
    MONTH_NUM        NUMBER(2,0),
    MONTH_NAME       STRING,
    WEEK_NUM         NUMBER(2,0),
    DAY_OF_MONTH     NUMBER(2,0),
    DAY_OF_WEEK      NUMBER(1,0),
    DAY_NAME         STRING
);