use warehouse retail_project;
use database retail_intelligence_db;
use schema staging;

CREATE OR REPLACE PROCEDURE SP_REFRESH_RETAIL_STAGE()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN

    INSERT OVERWRITE INTO STAGING.STG_PRODUCTS
    SELECT
        TRIM(PRODUCT_ID),
        TRIM(PRODUCT_NAME),
        TRIM(CATEGORY),
        TRIM(SUBCATEGORY),
        TRIM(BRAND),
        UNIT_COST,
        UNIT_PRICE,
        TRIM(SIZE),
        TRIM(COLOR)
    FROM RAW.RAW_PRODUCTS
    WHERE PRODUCT_ID IS NOT NULL;

    INSERT OVERWRITE INTO STAGING.STG_STORES
    SELECT
        TRIM(STORE_ID),
        TRIM(STORE_NAME),
        TRIM(CITY),
        TRIM(STATE),
        TRIM(REGION),
        TRIM(STORE_TYPE),
        OPENED_YEAR
    FROM RAW.RAW_STORES
    WHERE STORE_ID IS NOT NULL;

    INSERT OVERWRITE INTO STAGING.STG_SALES
    SELECT
        TRIM(TRANSACTION_ID),
        TRANSACTION_DATE,
        TRIM(STORE_ID),
        TRIM(PRODUCT_ID),
        UNITS_SOLD,
        GROSS_SALES_AMOUNT,
        DISCOUNT_AMOUNT,
        SALES_AMOUNT,
        TRIM(SALES_CHANNEL)
    FROM RAW.RAW_SALES_TRANSACTIONS
    WHERE TRANSACTION_ID IS NOT NULL
      AND SALES_AMOUNT >= 0;

    INSERT OVERWRITE INTO STAGING.STG_INVENTORY
    SELECT
        SNAPSHOT_DATE,
        TRIM(STORE_ID),
        TRIM(PRODUCT_ID),
        AVAILABLE_STOCK,
        ON_HAND_STOCK,
        RESERVED_STOCK,
        COMMITTED_STOCK,
        INVENTORY_ON_ORDER,
        SAFETY_STOCK
    FROM RAW.RAW_INVENTORY_SNAPSHOTS
    WHERE STORE_ID IS NOT NULL;

    INSERT OVERWRITE INTO STAGING.STG_SUPPLIER_LEAD_TIMES
    SELECT
    f.value:product_id::STRING AS PRODUCT_ID,
    f.value:supplier_name::STRING AS SUPPLIER_NAME,
    f.value:lead_time_days::NUMBER AS LEAD_TIME_DAYS,
    f.value:reorder_threshold::NUMBER AS REORDER_THRESHOLD,
    f.value:preferred_supplier::BOOLEAN AS PREFERRED_SUPPLIER,
    f.value:minimum_order_qty::NUMBER AS MINIMUM_ORDER_QTY
FROM RAW.RAW_SUPPLIER_LEAD_TIMES,
LATERAL FLATTEN(input => SRC) f;

      RETURN 'Retail Staged refreshed successfully';

END;
$$;

Create or replace procedure mart_load()
returns string
language SQL
EXECUTE AS CALLER
AS
$$
BEGIN

    INSERT OVERWRITE INTO MART.DIM_PRODUCT
    SELECT DISTINCT
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        SUBCATEGORY,
        BRAND,
        SIZE,
        COLOR,
        UNIT_COST,
        UNIT_PRICE
    FROM STAGING.STG_PRODUCTS;

    INSERT OVERWRITE INTO MART.DIM_STORE
    SELECT DISTINCT
        STORE_ID,
        STORE_NAME,
        CITY,
        STATE,
        REGION,
        STORE_TYPE,
        OPENED_YEAR
    FROM STAGING.STG_STORES;

    INSERT OVERWRITE INTO MART.FACT_SALES
    SELECT
        TRANSACTION_ID,
        TRANSACTION_DATE,
        STORE_ID,
        PRODUCT_ID,
        UNITS_SOLD,
        GROSS_SALES_AMOUNT,
        DISCOUNT_AMOUNT,
        SALES_AMOUNT,
        SALES_CHANNEL
    FROM STAGING.STG_SALES;

    INSERT OVERWRITE INTO MART.FACT_INVENTORY_DAILY
    SELECT
        SNAPSHOT_DATE,
        STORE_ID,
        PRODUCT_ID,
        AVAILABLE_STOCK,
        ON_HAND_STOCK,
        RESERVED_STOCK,
        COMMITTED_STOCK,
        INVENTORY_ON_ORDER,
        SAFETY_STOCK
    FROM STAGING.STG_INVENTORY;

    RETURN 'MART Load Successful';

    END;
    $$;

CREATE OR REPLACE TASK TASK_STAGING_LOAD
WAREHOUSE = RETAIL_PROJECT
SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
CALL RETAIL_INTELLIGENCE_DB.STAGING.SP_REFRESH_RETAIL_STAGE();

CREATE OR REPLACE TASK TASK_LOAD_RETAIL_MART
WAREHOUSE = RETAIL_PROJECT
AFTER TASK_STAGING_LOAD
AS
CALL RETAIL_INTELLIGENCE_DB.STAGING.MART_LOAD();

Alter task TASK_LOAD_RETAIL_MART suspend;

Alter task TASK_LOAD_RETAIL_MART resume;

EXECUTE task TASK_STAGING_LOAD;

call SP_REFRESH_RETAIL_STAGE();

call mart_load();

SHOW tasks;

Create or replace task update_date
WAREHOUSE = RETAIL_PROJECT
after RETAIL_INTELLIGENCE_DB.STAGING.TASK_STAGING_LOAD
AS
call RETAIL_INTELLIGENCE_DB.MART.date_update();
