USE WAREHOUSE RETAIL_PROJECT;
USE DATABASE RETAIL_INTELLIGENCE_DB;

CREATE OR REPLACE VIEW MART.VW_SALES_PERFORMANCE AS
SELECT
    f.TRANSACTION_DATE,
    d.YEAR_NUM,
    d.QUARTER_NUM,
    d.MONTH_NUM,
    d.MONTH_NAME,
    f.STORE_ID,
    s.STORE_NAME,
    s.REGION,
    f.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    SUM(f.UNITS_SOLD) AS TOTAL_UNITS_SOLD,
    SUM(f.GROSS_SALES_AMOUNT) AS TOTAL_GROSS_SALES,
    SUM(f.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,
    SUM(f.SALES_AMOUNT) AS TOTAL_NET_SALES
FROM MART.FACT_SALES f
LEFT JOIN MART.DIM_DATE d
    ON f.TRANSACTION_DATE = d.DATE_DAY
LEFT JOIN MART.DIM_STORE s
    ON f.STORE_ID = s.STORE_ID
LEFT JOIN MART.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    f.TRANSACTION_DATE,
    d.YEAR_NUM,
    d.QUARTER_NUM,
    d.MONTH_NUM,
    d.MONTH_NAME,
    f.STORE_ID,
    s.STORE_NAME,
    s.REGION,
    f.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY;