USE WAREHOUSE RETAIL_PROJECT;
USE DATABASE RETAIL_INTELLIGENCE_DB;
USE schema raw;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::934347069737:role/sf_int'
    STORAGE_ALLOWED_LOCATIONS = ('s3://sf-reatil-project-stage/raw/');

    DESC INTEGRATION S3_INT;

-- Stage Creation

CREATE OR REPLACE STAGE AWS_EXT_STAGE
    URL = 's3://sf-reatil-project-stage/raw/'
    STORAGE_INTEGRATION = S3_INT;

Drop stage retail_ext_stage;

list @AWS_EXT_STAGE;

