USE WAREHOUSE RETAIL_PROJECT;
USE DATABASE RETAIL_INTELLIGENCE_DB;
USE schema raw;

COPY INTO RETAIL_INTELLIGENCE_DB.RAW.RAW_PRODUCTS
FROM @AWS_EXT_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RETAIL_INTELLIGENCE_DB.RAW.RAW_STORES
FROM @AWS_EXT_STAGE/stores.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RETAIL_INTELLIGENCE_DB.RAW.RAW_SALES_TRANSACTIONS
FROM @AWS_EXT_STAGE/sales_transactions.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RETAIL_INTELLIGENCE_DB.RAW.RAW_INVENTORY_SNAPSHOTS
FROM @AWS_EXT_STAGE/inventory_snapshots.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO RETAIL_INTELLIGENCE_DB.RAW.RAW_SUPPLIER_LEAD_TIMES
FROM @AWS_EXT_STAGE/supplier_lead_times.json
FILE_FORMAT = (FORMAT_NAME = RAW.JSON_FORMAT)
ON_ERROR = 'CONTINUE';