USE WAREHOUSE RETAIL_PROJECT;
USE DATABASE RETAIL_INTELLIGENCE_DB;

CREATE OR REPLACE VIEW MART.VW_INVENTORY_HEALTH AS
SELECT
    i.SNAPSHOT_DATE,
    i.STORE_ID,
    s.STORE_NAME,
    s.REGION,
    i.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    i.AVAILABLE_STOCK,
    i.ON_HAND_STOCK,
    i.RESERVED_STOCK,
    i.COMMITTED_STOCK,
    i.INVENTORY_ON_ORDER,
    i.SAFETY_STOCK,
    CASE
        WHEN i.AVAILABLE_STOCK = 0 THEN 'OUT OF STOCK'
        WHEN i.AVAILABLE_STOCK <= i.SAFETY_STOCK THEN 'LOW STOCK'
        ELSE 'HEALTHY'
    END AS STOCK_STATUS
FROM MART.FACT_INVENTORY_DAILY i
LEFT JOIN MART.DIM_PRODUCT p
    ON i.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN MART.DIM_STORE s
    ON i.STORE_ID = s.STORE_ID;


CREATE OR REPLACE VIEW MART.VW_LOW_STOCK_ALERTS AS
WITH LATEST_INVENTORY AS (
    SELECT
        SNAPSHOT_DATE,
        STORE_ID,
        PRODUCT_ID,
        AVAILABLE_STOCK,
        ON_HAND_STOCK,
        RESERVED_STOCK,
        COMMITTED_STOCK,
        INVENTORY_ON_ORDER,
        SAFETY_STOCK,
        ROW_NUMBER() OVER (
            PARTITION BY STORE_ID, PRODUCT_ID
            ORDER BY SNAPSHOT_DATE DESC
        ) AS RN
    FROM MART.FACT_INVENTORY_DAILY
)
SELECT
    i.SNAPSHOT_DATE,
    i.STORE_ID,
    s.STORE_NAME,
    s.REGION,
    i.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    i.AVAILABLE_STOCK,
    i.SAFETY_STOCK,
    i.INVENTORY_ON_ORDER,
    CASE
        WHEN i.AVAILABLE_STOCK = 0 THEN 'OUT OF STOCK'
        WHEN i.AVAILABLE_STOCK <= i.SAFETY_STOCK THEN 'LOW STOCK'
        ELSE 'HEALTHY'
    END AS ALERT_STATUS
FROM LATEST_INVENTORY i
JOIN MART.DIM_STORE s
    ON i.STORE_ID = s.STORE_ID
JOIN MART.DIM_PRODUCT p
    ON i.PRODUCT_ID = p.PRODUCT_ID
WHERE i.RN = 1
  AND i.AVAILABLE_STOCK <= i.SAFETY_STOCK;
