USE WAREHOUSE RETAIL_PROJECT;
USE DATABASE RETAIL_INTELLIGENCE_DB;

CREATE OR REPLACE VIEW MART.VW_REORDER_RECOMMENDATIONS AS
WITH SALES_VELOCITY AS (
    SELECT
        STORE_ID,
        PRODUCT_ID,
        AVG(UNITS_SOLD) AS AVG_DAILY_UNITS_SOLD
    FROM MART.FACT_SALES
    GROUP BY STORE_ID, PRODUCT_ID
),
LATEST_INVENTORY AS (
    SELECT
        SNAPSHOT_DATE,
        STORE_ID,
        PRODUCT_ID,
        AVAILABLE_STOCK,
        ON_HAND_STOCK,
        RESERVED_STOCK,
        COMMITTED_STOCK,
        INVENTORY_ON_ORDER,
        SAFETY_STOCK,
        ROW_NUMBER() OVER (
            PARTITION BY STORE_ID, PRODUCT_ID
            ORDER BY SNAPSHOT_DATE DESC
        ) AS RN
    FROM MART.FACT_INVENTORY_DAILY
)
SELECT
    i.SNAPSHOT_DATE,
    i.STORE_ID,
    s.STORE_NAME,
    s.REGION,
    i.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    i.AVAILABLE_STOCK,
    i.ON_HAND_STOCK,
    i.RESERVED_STOCK,
    i.COMMITTED_STOCK,
    i.INVENTORY_ON_ORDER,
    i.SAFETY_STOCK,
    COALESCE(v.AVG_DAILY_UNITS_SOLD, 0) AS AVG_DAILY_UNITS_SOLD,
    slt.SUPPLIER_NAME,
    slt.LEAD_TIME_DAYS,
    slt.REORDER_THRESHOLD,
    slt.MINIMUM_ORDER_QTY,
    CASE
        WHEN COALESCE(v.AVG_DAILY_UNITS_SOLD, 0) = 0 THEN NULL
        ELSE ROUND(i.AVAILABLE_STOCK / v.AVG_DAILY_UNITS_SOLD, 2)
    END AS DAYS_OF_COVER,
    CASE
        WHEN i.AVAILABLE_STOCK <= COALESCE(slt.REORDER_THRESHOLD, i.SAFETY_STOCK)
            THEN 'REORDER'
        ELSE 'NO ACTION'
    END AS REORDER_FLAG
FROM LATEST_INVENTORY i
LEFT JOIN SALES_VELOCITY v
    ON i.STORE_ID = v.STORE_ID
   AND i.PRODUCT_ID = v.PRODUCT_ID
LEFT JOIN MART.DIM_PRODUCT p
    ON i.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN MART.DIM_STORE s
    ON i.STORE_ID = s.STORE_ID
LEFT JOIN STAGING.STG_SUPPLIER_LEAD_TIMES slt
    ON i.PRODUCT_ID = slt.PRODUCT_ID
WHERE i.RN = 1;