USE WAREHOUSE RETAIL_PROJECT;
USE DATABASE RETAIL_INTELLIGENCE_DB;
USE SCHEMA STAGING;

CREATE OR REPLACE transient TABLE STAGING.STG_PRODUCTS (
    PRODUCT_ID      STRING,
    PRODUCT_NAME    STRING,
    CATEGORY        STRING,
    SUBCATEGORY     STRING,
    BRAND           STRING,
    UNIT_COST       NUMBER(10,2),
    UNIT_PRICE      NUMBER(10,2),
    SIZE            STRING,
    COLOR           STRING
);

CREATE OR REPLACE transient TABLE STAGING.STG_STORES (
    STORE_ID        STRING,
    STORE_NAME      STRING,
    CITY            STRING,
    STATE           STRING,
    REGION          STRING,
    STORE_TYPE      STRING,
    OPENED_YEAR     NUMBER(4,0)
);

CREATE OR REPLACE transient TABLE STAGING.STG_SALES (
    TRANSACTION_ID       STRING,
    TRANSACTION_DATE     DATE,
    STORE_ID             STRING,
    PRODUCT_ID           STRING,
    UNITS_SOLD           NUMBER(10,0),
    GROSS_SALES_AMOUNT   NUMBER(12,2),
    DISCOUNT_AMOUNT      NUMBER(12,2),
    SALES_AMOUNT         NUMBER(12,2),
    SALES_CHANNEL        STRING
);

CREATE OR REPLACE transient TABLE STAGING.STG_INVENTORY (
    SNAPSHOT_DATE        DATE,
    STORE_ID             STRING,
    PRODUCT_ID           STRING,
    AVAILABLE_STOCK      NUMBER(10,0),
    ON_HAND_STOCK        NUMBER(10,0),
    RESERVED_STOCK       NUMBER(10,0),
    COMMITTED_STOCK      NUMBER(10,0),
    INVENTORY_ON_ORDER   NUMBER(10,0),
    SAFETY_STOCK         NUMBER(10,0)
);

CREATE OR REPLACE transient TABLE STAGING.STG_SUPPLIER_LEAD_TIMES (
    PRODUCT_ID           STRING,
    SUPPLIER_NAME        STRING,
    LEAD_TIME_DAYS       NUMBER(10,0),
    REORDER_THRESHOLD    NUMBER(10,0),
    PREFERRED_SUPPLIER   BOOLEAN,
    MINIMUM_ORDER_QTY    NUMBER(10,0)
);