USE WAREHOUSE RETAIL_PROJECT;
USE DATABASE RETAIL_INTELLIGENCE_DB;

CREATE OR REPLACE VIEW MART.VW_STORE_PRODUCT_TRENDS AS
WITH DAILY_SALES AS (
    SELECT
        f.TRANSACTION_DATE,
        f.STORE_ID,
        ds.STORE_NAME,
        ds.REGION,
        f.PRODUCT_ID,
        dp.PRODUCT_NAME,
        dp.CATEGORY,
        SUM(f.UNITS_SOLD) AS DAILY_UNITS_SOLD,
        SUM(f.SALES_AMOUNT) AS DAILY_SALES_AMOUNT
    FROM MART.FACT_SALES f
    JOIN MART.DIM_STORE ds
        ON f.STORE_ID = ds.STORE_ID
    JOIN MART.DIM_PRODUCT dp
        ON f.PRODUCT_ID = dp.PRODUCT_ID
    GROUP BY
        f.TRANSACTION_DATE,
        f.STORE_ID,
        ds.STORE_NAME,
        ds.REGION,
        f.PRODUCT_ID,
        dp.PRODUCT_NAME,
        dp.CATEGORY
),
ROLLING_TREND AS (
    SELECT
        TRANSACTION_DATE,
        STORE_ID,
        STORE_NAME,
        REGION,
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        DAILY_UNITS_SOLD,
        DAILY_SALES_AMOUNT,
        AVG(DAILY_UNITS_SOLD) OVER (
            PARTITION BY STORE_ID, PRODUCT_ID
            ORDER BY TRANSACTION_DATE
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ) AS ROLLING_7D_AVG_UNITS,
        AVG(DAILY_SALES_AMOUNT) OVER (
            PARTITION BY STORE_ID, PRODUCT_ID
            ORDER BY TRANSACTION_DATE
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ) AS ROLLING_7D_AVG_SALES
    FROM DAILY_SALES
)
SELECT *
FROM ROLLING_TREND;

CREATE OR REPLACE VIEW MART.VW_TOP_STORE_PERFORMANCE AS
SELECT
    s.STORE_ID,
    s.STORE_NAME,
    s.REGION,
    COUNT(DISTINCT f.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(f.UNITS_SOLD) AS TOTAL_UNITS_SOLD,
    SUM(f.SALES_AMOUNT) AS TOTAL_NET_SALES,
    ROUND(AVG(f.SALES_AMOUNT), 2) AS AVG_TRANSACTION_VALUE
FROM MART.FACT_SALES f
JOIN MART.DIM_STORE s
    ON f.STORE_ID = s.STORE_ID
GROUP BY
    s.STORE_ID,
    s.STORE_NAME,
    s.REGION;


CREATE OR REPLACE VIEW MART.VW_CATEGORY_SALES_SUMMARY AS
SELECT
    d.YEAR_NUM,
    d.MONTH_NUM,
    d.MONTH_NAME,
    p.CATEGORY,
    SUM(f.UNITS_SOLD) AS TOTAL_UNITS_SOLD,
    SUM(f.GROSS_SALES_AMOUNT) AS TOTAL_GROSS_SALES,
    SUM(f.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,
    SUM(f.SALES_AMOUNT) AS TOTAL_NET_SALES
FROM MART.FACT_SALES f
JOIN MART.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
JOIN MART.DIM_DATE d
    ON f.TRANSACTION_DATE = d.DATE_DAY
GROUP BY
    d.YEAR_NUM,
    d.MONTH_NUM,
    d.MONTH_NAME,
    p.CATEGORY;