USE WAREHOUSE RETAIL_PROJECT;
USE DATABASE RETAIL_INTELLIGENCE_DB;

-- 1. RAW LAYER ROW COUNT CHECKS

SELECT 'RAW_PRODUCTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RAW.RAW_PRODUCTS

UNION ALL

SELECT 'RAW_STORES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RAW.RAW_STORES

UNION ALL

SELECT 'RAW_SALES_TRANSACTIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RAW.RAW_SALES_TRANSACTIONS

UNION ALL

SELECT 'RAW_INVENTORY_SNAPSHOTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RAW.RAW_INVENTORY_SNAPSHOTS

UNION ALL

SELECT 'RAW_SUPPLIER_LEAD_TIMES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RAW.RAW_SUPPLIER_LEAD_TIMES;


-- 2. STAGING LAYER ROW COUNT CHECKS

SELECT 'STG_PRODUCTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STAGING.STG_PRODUCTS

UNION ALL

SELECT 'STG_STORES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STAGING.STG_STORES

UNION ALL

SELECT 'STG_SALES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STAGING.STG_SALES

UNION ALL

SELECT 'STG_INVENTORY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STAGING.STG_INVENTORY

UNION ALL

SELECT 'STG_SUPPLIER_LEAD_TIMES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM STAGING.STG_SUPPLIER_LEAD_TIMES;



-- 3. MART LAYER ROW COUNT CHECKS

SELECT 'DIM_PRODUCT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM MART.DIM_PRODUCT

UNION ALL

SELECT 'DIM_STORE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM MART.DIM_STORE

UNION ALL

SELECT 'DIM_DATE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM MART.DIM_DATE

UNION ALL

SELECT 'FACT_SALES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM MART.FACT_SALES

UNION ALL

SELECT 'FACT_INVENTORY_DAILY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM MART.FACT_INVENTORY_DAILY;


-- 4. RAW VS STAGING COUNT RECONCILIATION

SELECT 'PRODUCTS' AS DATASET,
       (SELECT COUNT(*) FROM RAW.RAW_PRODUCTS) AS RAW_COUNT,
       (SELECT COUNT(*) FROM STAGING.STG_PRODUCTS) AS STAGING_COUNT

UNION ALL

SELECT 'STORES' AS DATASET,
       (SELECT COUNT(*) FROM RAW.RAW_STORES) AS RAW_COUNT,
       (SELECT COUNT(*) FROM STAGING.STG_STORES) AS STAGING_COUNT

UNION ALL

SELECT 'SALES' AS DATASET,
       (SELECT COUNT(*) FROM RAW.RAW_SALES_TRANSACTIONS) AS RAW_COUNT,
       (SELECT COUNT(*) FROM STAGING.STG_SALES) AS STAGING_COUNT

UNION ALL

SELECT 'INVENTORY' AS DATASET,
       (SELECT COUNT(*) FROM RAW.RAW_INVENTORY_SNAPSHOTS) AS RAW_COUNT,
       (SELECT COUNT(*) FROM STAGING.STG_INVENTORY) AS STAGING_COUNT

UNION ALL

SELECT 'SUPPLIER' AS DATASET,
       (SELECT COUNT(*) FROM RAW.RAW_SUPPLIER_LEAD_TIMES) AS RAW_COUNT,
       (SELECT COUNT(*) FROM STAGING.STG_SUPPLIER_LEAD_TIMES) AS STAGING_COUNT;


-- 5. NULL CHECKS ON PRIMARY BUSINESS KEYS

SELECT 'STG_PRODUCTS.PRODUCT_ID' AS CHECK_NAME, COUNT(*) AS NULL_COUNT
FROM STAGING.STG_PRODUCTS
WHERE PRODUCT_ID IS NULL

UNION ALL

SELECT 'STG_STORES.STORE_ID' AS CHECK_NAME, COUNT(*) AS NULL_COUNT
FROM STAGING.STG_STORES
WHERE STORE_ID IS NULL

UNION ALL

SELECT 'STG_SALES.TRANSACTION_ID' AS CHECK_NAME, COUNT(*) AS NULL_COUNT
FROM STAGING.STG_SALES
WHERE TRANSACTION_ID IS NULL

UNION ALL

SELECT 'STG_SALES.PRODUCT_ID' AS CHECK_NAME, COUNT(*) AS NULL_COUNT
FROM STAGING.STG_SALES
WHERE PRODUCT_ID IS NULL

UNION ALL

SELECT 'STG_SALES.STORE_ID' AS CHECK_NAME, COUNT(*) AS NULL_COUNT
FROM STAGING.STG_SALES
WHERE STORE_ID IS NULL

UNION ALL

SELECT 'STG_INVENTORY.PRODUCT_ID' AS CHECK_NAME, COUNT(*) AS NULL_COUNT
FROM STAGING.STG_INVENTORY
WHERE PRODUCT_ID IS NULL

UNION ALL

SELECT 'STG_INVENTORY.STORE_ID' AS CHECK_NAME, COUNT(*) AS NULL_COUNT
FROM STAGING.STG_INVENTORY
WHERE STORE_ID IS NULL;


-- 6. DUPLICATE CHECKS

SELECT TRANSACTION_ID, COUNT(*) AS RECORD_COUNT
FROM STAGING.STG_SALES
GROUP BY TRANSACTION_ID
HAVING COUNT(*) > 1
ORDER BY RECORD_COUNT DESC;


SELECT PRODUCT_ID, COUNT(*) AS RECORD_COUNT
FROM MART.DIM_PRODUCT
GROUP BY PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY RECORD_COUNT DESC;


SELECT STORE_ID, COUNT(*) AS RECORD_COUNT
FROM MART.DIM_STORE
GROUP BY STORE_ID
HAVING COUNT(*) > 1
ORDER BY RECORD_COUNT DESC;



-- 7. ORPHAN KEY CHECKS IN FACT TABLES

SELECT COUNT(*) AS INVALID_PRODUCT_KEYS_IN_FACT_SALES
FROM MART.FACT_SALES f
LEFT JOIN MART.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL;


SELECT COUNT(*) AS INVALID_STORE_KEYS_IN_FACT_SALES
FROM MART.FACT_SALES f
LEFT JOIN MART.DIM_STORE s
    ON f.STORE_ID = s.STORE_ID
WHERE s.STORE_ID IS NULL;


SELECT COUNT(*) AS INVALID_PRODUCT_KEYS_IN_FACT_INVENTORY
FROM MART.FACT_INVENTORY_DAILY i
LEFT JOIN MART.DIM_PRODUCT p
    ON i.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL;


SELECT COUNT(*) AS INVALID_STORE_KEYS_IN_FACT_INVENTORY
FROM MART.FACT_INVENTORY_DAILY i
LEFT JOIN MART.DIM_STORE s
    ON i.STORE_ID = s.STORE_ID
WHERE s.STORE_ID IS NULL;


-- 8. NEGATIVE VALUE CHECKS

SELECT COUNT(*) AS NEGATIVE_UNITS_SOLD
FROM STAGING.STG_SALES
WHERE UNITS_SOLD < 0;


SELECT COUNT(*) AS NEGATIVE_SALES_AMOUNT
FROM STAGING.STG_SALES
WHERE SALES_AMOUNT < 0;


SELECT COUNT(*) AS NEGATIVE_AVAILABLE_STOCK
FROM STAGING.STG_INVENTORY
WHERE AVAILABLE_STOCK < 0;


SELECT COUNT(*) AS NEGATIVE_ON_HAND_STOCK
FROM STAGING.STG_INVENTORY
WHERE ON_HAND_STOCK < 0;


SELECT COUNT(*) AS NEGATIVE_RESERVED_STOCK
FROM STAGING.STG_INVENTORY
WHERE RESERVED_STOCK < 0;


SELECT COUNT(*) AS NEGATIVE_COMMITTED_STOCK
FROM STAGING.STG_INVENTORY
WHERE COMMITTED_STOCK < 0;


SELECT COUNT(*) AS NEGATIVE_INVENTORY_ON_ORDER
FROM STAGING.STG_INVENTORY
WHERE INVENTORY_ON_ORDER < 0;



-- 10. DIM_DATE VALIDATION


SELECT MIN(DATE_DAY) AS MIN_DATE,
       MAX(DATE_DAY) AS MAX_DATE,
       COUNT(*) AS TOTAL_DATES
FROM MART.DIM_DATE;


SELECT COUNT(*) AS MISSING_SALES_DATES_IN_DIM_DATE
FROM (
    SELECT DISTINCT TRANSACTION_DATE AS DATE_DAY
    FROM MART.FACT_SALES
) s
LEFT JOIN MART.DIM_DATE d
    ON s.DATE_DAY = d.DATE_DAY
WHERE d.DATE_DAY IS NULL;


SELECT COUNT(*) AS MISSING_INVENTORY_DATES_IN_DIM_DATE
FROM (
    SELECT DISTINCT SNAPSHOT_DATE AS DATE_DAY
    FROM MART.FACT_INVENTORY_DAILY
) i
LEFT JOIN MART.DIM_DATE d
    ON i.DATE_DAY = d.DATE_DAY
WHERE d.DATE_DAY IS NULL;



-- 11. SUPPLIER DATA VALIDATION

SELECT COUNT(*) AS NULL_SUPPLIER_PRODUCT_IDS
FROM STAGING.STG_SUPPLIER_LEAD_TIMES
WHERE PRODUCT_ID IS NULL;


SELECT COUNT(*) AS NULL_LEAD_TIMES
FROM STAGING.STG_SUPPLIER_LEAD_TIMES
WHERE LEAD_TIME_DAYS IS NULL;


SELECT COUNT(*) AS NEGATIVE_LEAD_TIMES
FROM STAGING.STG_SUPPLIER_LEAD_TIMES
WHERE LEAD_TIME_DAYS < 0;


-- 12. MART-LEVEL BUSINESS SANITY CHECKS


SELECT COUNT(*) AS NULL_STORE_NAMES_IN_SALES_VIEW
FROM MART.VW_SALES_PERFORMANCE
WHERE STORE_NAME IS NULL;


SELECT COUNT(*) AS NULL_PRODUCT_NAMES_IN_INVENTORY_VIEW
FROM MART.VW_INVENTORY_HEALTH
WHERE PRODUCT_NAME IS NULL;


SELECT COUNT(*) AS REORDER_ROWS_WITHOUT_PRODUCT
FROM MART.VW_REORDER_RECOMMENDATIONS
WHERE PRODUCT_NAME IS NULL;


-- 13. TOP-LEVEL SUMMARY CHECKS

SELECT
    (SELECT COUNT(*) FROM MART.FACT_SALES) AS FACT_SALES_COUNT,
    (SELECT COUNT(*) FROM MART.FACT_INVENTORY_DAILY) AS FACT_INVENTORY_COUNT,
    (SELECT COUNT(*) FROM MART.DIM_PRODUCT) AS DIM_PRODUCT_COUNT,
    (SELECT COUNT(*) FROM MART.DIM_STORE) AS DIM_STORE_COUNT,
    (SELECT COUNT(*) FROM MART.DIM_DATE) AS DIM_DATE_COUNT;


-- 14. SAMPLE RECONCILIATION CHECKS

SELECT
    SUM(SALES_AMOUNT) AS TOTAL_NET_SALES,
    SUM(GROSS_SALES_AMOUNT) AS TOTAL_GROSS_SALES,
    SUM(DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT
FROM MART.FACT_SALES;


SELECT
    STOCK_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM MART.VW_INVENTORY_HEALTH
GROUP BY STOCK_STATUS
ORDER BY RECORD_COUNT DESC;


SELECT
    REORDER_FLAG,
    COUNT(*) AS RECORD_COUNT
FROM MART.VW_REORDER_RECOMMENDATIONS
GROUP BY REORDER_FLAG
ORDER BY RECORD_COUNT DESC;